# First attempt at using Github actions
# This

name: BuildAndTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Go tools
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          # Versioning follows https://github.com/npm/node-semver
          go-version: '1.19.x' # The Go version to download and use.

      - name: Install dependencies
        run: |
          make install_tools

      - name: Check code quality
        run: |
          make lint

      - name: Check tests
        run: |
          make test_clean

      # TODO: Add a step to build the code once there is enough code!

